### ISSUE TITLE
Short between D11 and LED pin

### ISSUE THREAD

**Issue by ondras12345** [nostradomus/ATtinyISPprogrammerShield#1]
There is a short in the PCB design
![attiny_prog_issue](https://user-images.githubusercontent.com/44524735/50575758-75c4ca80-0e04-11e9-89e5-4ac80226e929.png)

**Comment by nostradomus** [comment]
@ondras12345,
thank you for your remark.
Version V02 of this project has now been released, and does no longer contain the problem (short between LED3 and D11). All related files have been replaced in the repo, and readme's have been updated.
